services:
  db:
    container_name: postgres
    image: postgres:17.5
    environment:
      POSTGRES_USER: whisper
      POSTGRES_PASSWORD: password
      POSTGRES_DB: whisper
    volumes:
      - db:/var/lib/postgresql/data
      - userData:/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-whisper} -d ${POSTGRES_DB:-whisper}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - db

  api:
    build: ./api
    container_name: api
    restart: unless-stopped
    env_file:
      - api/.env
    environment:
      DB_HOST: db
      DB_USER: whisper
      DB_PASSWORD: password
      DB_NAME: whisper
    ports:
      - "3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db
      - api
  nginx:
    image: nginx:1.28
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    depends_on:
      - api
    networks:
      - api

networks:
  db:
    driver: bridge
  api:
    driver: bridge
volumes:
  db:
    driver: local
  userData:
    driver: local