services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: whisper
      POSTGRES_PASSWORD: password
      POSTGRES_DB: whisper
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    command: /bin/bash -c "until pg_isready -U ${POSTGRES_USER} -p 5432; do sleep 1; done; psql -U ${POSTGRES_USER} -c 'CREATE DATABASE ${POSTGRES_DB};"
    networks:
      - db
  
  backend:
    build: ./api
    container_name: api
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USER: whisper
      DB_PASSWORD: password
      DB_NAME: whisper
    ports:
      - "3000"
    depends_on:
      - db
    networks:
      - db
      - api
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - api

networks:
  db:
    driver: bridge
  api:
    driver: bridge